project 'JGWebAndJS.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'JGWebAndJS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JGWebAndJS

  pod 'WebViewJavascriptBridge', '~> 6.0'
  


  target 'JGWebAndJSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JGWebAndJSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
